# Generated by Django 2.2.3 on 2019-07-23 14:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('headline_pic', models.ImageField(upload_to='static/img/headline_image', verbose_name='Headline Picture')),
                ('created_date', models.DateField(verbose_name=datetime.datetime(2019, 7, 23, 14, 49, 13, 449750, tzinfo=utc))),
                ('comment', models.IntegerField(default=0)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=25)),
                ('prof_pic', models.ImageField(upload_to='static/img/mentee_image')),
                ('kesan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=25)),
                ('prof_pic', models.ImageField(upload_to='static/img/mentor_image')),
                ('sebutan', models.CharField(max_length=50)),
                ('pengalaman', models.IntegerField()),
                ('quote', models.TextField()),
            ],
        ),
    ]
